name: Build

on:
  push:
    branches:
      - release**

jobs:
  java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - run: java -version
      - run: mvn -v
      - run: mvn -B verify -Dgpg.skip=true
